# Generated by Django 6.0.1 on 2026-01-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.enrollment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment',), name='unique_review_per_enrollment')],
            },
        ),
    ]
