# Generated by Django 6.0.1 on 2026-01-17 11:55

import django.db.models.deletion
from django.db import migrations, models


def add_role_column_if_missing(apps, schema_editor):
    cursor = schema_editor.connection.cursor()

    # Check if column exists differently for PostgreSQL vs SQLite
    table_name = 'accounts_user'
    column_name = 'role_id'

    # Check if column exists in PostgreSQL
    cursor.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_name=%s AND column_name=%s",
        [table_name, column_name]
    )
    column_exists = cursor.fetchone() is not None

    if column_exists:
        return

    cursor.execute(
        "ALTER TABLE accounts_user ADD COLUMN role_id integer"
    )
    cursor.execute(
        "SELECT role_id FROM dictionaries_role WHERE code = 'student'"
    )
    row = cursor.fetchone()
    if row:
        role_id = row[0]
    else:
        cursor.execute(
            "INSERT INTO dictionaries_role (code, name) VALUES ('student', 'Student') RETURNING role_id"
        )
        role_id = cursor.fetchone()[0]

    cursor.execute(
        "UPDATE accounts_user SET role_id = %s WHERE role_id IS NULL",
        [role_id],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("dictionaries", "0004_role"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_role_column_if_missing, migrations.RunPython.noop)
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="role",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionaries.role",
                    ),
                ),
            ],
        ),
    ]
