# Generated by Django 6.0.1 on 2026-01-17 00:00

from django.db import migrations


def create_active_status(apps, schema_editor):
    UserStatus = apps.get_model("dictionaries", "UserStatus")
    UserStatus.objects.get_or_create(code="active", defaults={"name": "Active"})


def remove_active_status(apps, schema_editor):
    UserStatus = apps.get_model("dictionaries", "UserStatus")
    UserStatus.objects.filter(code="active").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_active_status, remove_active_status),
    ]
