# Generated by Django 6.0.1 on 2026-01-17 00:10

from django.db import migrations


DEFAULT_CATEGORIES = [
    "Programming",
    "Data Science",
    "Design",
    "Marketing",
    "Business",
    "DevOps",
]


def _replace_anyany(model, field_name):
    if field_name in {f.name for f in model._meta.fields}:
        model.objects.filter(**{field_name: "AnyAny"}).update(**{field_name: "Any"})


def seed_categories_and_fix_anyany(apps, schema_editor):
    Category = apps.get_model("dictionaries", "Category")
    UserStatus = apps.get_model("dictionaries", "UserStatus")
    CourseLevel = apps.get_model("dictionaries", "CourseLevel")
    AssignmentType = apps.get_model("dictionaries", "AssignmentType")
    EnrollmentStatus = apps.get_model("dictionaries", "EnrollmentStatus")
    Language = apps.get_model("dictionaries", "Language")

    for model in [
        UserStatus,
        CourseLevel,
        AssignmentType,
        EnrollmentStatus,
        Language,
        Category,
    ]:
        _replace_anyany(model, "code")
        _replace_anyany(model, "name")

    for name in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name)


def unseed_categories_and_fix_anyany(apps, schema_editor):
    Category = apps.get_model("dictionaries", "Category")
    for name in DEFAULT_CATEGORIES:
        Category.objects.filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0002_seed_user_status_active"),
    ]

    operations = [
        migrations.RunPython(seed_categories_and_fix_anyany, unseed_categories_and_fix_anyany),
    ]
