# Generated by Django 6.0.1 on 2026-01-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0003_seed_categories_and_fix_anyany"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    (
                        "CREATE TABLE IF NOT EXISTS dictionaries_role ("
                        '"role_id" SERIAL NOT NULL PRIMARY KEY, '
                        '"code" varchar(50) NOT NULL UNIQUE, '
                        '"name" varchar(150) NOT NULL'
                        ")"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    (
                        "INSERT INTO dictionaries_role (code, name) "
                        "SELECT 'student', 'Student' "
                        "WHERE NOT EXISTS ("
                        "SELECT 1 FROM dictionaries_role WHERE code = 'student'"
                        ")"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Role",
                    fields=[
                        ("role_id", models.AutoField(primary_key=True, serialize=False)),
                        ("code", models.CharField(max_length=50, unique=True)),
                        ("name", models.CharField(max_length=150)),
                    ],
                ),
            ],
        ),
    ]
