# Generated by Django 6.0.1 on 2026-01-17 00:20

from django.db import migrations


DEFAULT_LEVELS = [
    ("beginner", "Beginner"),
    ("intermediate", "Intermediate"),
    ("advanced", "Advanced"),
]

DEFAULT_LANGUAGES = [
    ("en", "English"),
    ("ru", "Russian"),
    ("uk", "Ukrainian"),
]


def seed_levels_languages(apps, schema_editor):
    CourseLevel = apps.get_model("dictionaries", "CourseLevel")
    Language = apps.get_model("dictionaries", "Language")

    for code, name in DEFAULT_LEVELS:
        CourseLevel.objects.get_or_create(code=code, defaults={"name": name})

    for code, name in DEFAULT_LANGUAGES:
        Language.objects.get_or_create(code=code, defaults={"name": name})


def unseed_levels_languages(apps, schema_editor):
    CourseLevel = apps.get_model("dictionaries", "CourseLevel")
    Language = apps.get_model("dictionaries", "Language")

    for code, _ in DEFAULT_LEVELS:
        CourseLevel.objects.filter(code=code).delete()

    for code, _ in DEFAULT_LANGUAGES:
        Language.objects.filter(code=code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0004_role"),
    ]

    operations = [
        migrations.RunPython(seed_levels_languages, unseed_levels_languages),
    ]
