# Generated by Django 6.0.1 on 2026-01-17 13:20

from django.db import migrations


DEFAULT_ASSIGNMENT_TYPES = [
    ("test", "Test"),
    ("essay", "Essay"),
    ("project", "Project"),
    ("homework", "Homework"),
    ("quiz", "Quiz"),
    ("presentation", "Presentation"),
]


def seed_assignment_types(apps, schema_editor):
    AssignmentType = apps.get_model("dictionaries", "AssignmentType")

    for code, name in DEFAULT_ASSIGNMENT_TYPES:
        AssignmentType.objects.get_or_create(code=code, defaults={"name": name})


def unseed_assignment_types(apps, schema_editor):
    AssignmentType = apps.get_model("dictionaries", "AssignmentType")

    for code, _ in DEFAULT_ASSIGNMENT_TYPES:
        AssignmentType.objects.filter(code=code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_seed_levels_languages'),
    ]

    operations = [
        migrations.RunPython(seed_assignment_types, unseed_assignment_types),
    ]
