# Generated by Django 6.0.1 on 2026-01-17 13:21

from django.db import migrations


DEFAULT_ENROLLMENT_STATUSES = [
    ("active", "Active"),
    ("completed", "Completed"),
    ("dropped", "Dropped"),
    ("paused", "Paused"),
]


def seed_enrollment_statuses(apps, schema_editor):
    EnrollmentStatus = apps.get_model("dictionaries", "EnrollmentStatus")

    for code, name in DEFAULT_ENROLLMENT_STATUSES:
        EnrollmentStatus.objects.get_or_create(code=code, defaults={"name": name})


def unseed_enrollment_statuses(apps, schema_editor):
    EnrollmentStatus = apps.get_model("dictionaries", "EnrollmentStatus")

    for code, _ in DEFAULT_ENROLLMENT_STATUSES:
        EnrollmentStatus.objects.filter(code=code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0006_auto_20260117_1420'),
    ]

    operations = [
        migrations.RunPython(seed_enrollment_statuses, unseed_enrollment_statuses),
    ]
